### ISSUE TITLE
Any plans for react 0.14 ?

### ISSUE THREAD

**Issue by Bulforce** [PearlVentures/Essence#36]

**Comment by hartmamt** [comment]
I think this project appears to have lost a lot of steam.  Our team has moved to material-ui.

**Comment by patrick-jones** [comment]
It's really too bad to see this project falter; material-ui is a bit of a mess if you ask me.

**Comment by raulmatei** [comment]
Sorry that no you've got no response for such a long time. We'll be releasing a new and improved version soon. Till then we'll probably release an intermediary version that supports React 0.14. 

Regards,
Raul.

**Comment by patrick-jones** [comment]
I think this project would benefit from opening it up to a wider community. I'd be willing to help out, and I suspect others would too. But people will only be willing to commit to it if there is real community involvement. At this point it feels like a private project that gets an occasional public dump.

**Comment by cloudtracer** [comment]
I've been silently following this project for awhile and was going to finally give it a spin with a new react project I'm working on, but I was really hoping to do it in React 0.14. I've been using material-ui for some of my production projects but I'd really like to move off it because I too agree that it is a mess and Essence has a simpler feel to it.  The chips UI element alone really makes me want to start using this, as finding I haven't been able to find a react compatible chip ui element outside of this project. If there was an async chips select component you'd get a lot of people using this..

Put me down as +1 for React 0.14.

**Comment by hetmann** [comment]
We updated Essence at React@0.14.3 version + the React-Essence NPM package (npm install react-essence@latest).

**Comment by raulmatei** [comment]
Please fill in separate issues, and if you want to help or bring in your own ideas please comment on #37. Any help will be appreciated.
